# 💖 赞助 Pluto 项目

感谢您对 Pluto 项目的关注和支持！您的赞助将帮助项目持续发展和维护。

## 🌟 赞助方式

### GitHub Sponsors
- **GitHub**: [https://github.com/sponsors/TongScriptX](https://github.com/sponsors/TongScriptX)

### 其他方式
- **支付宝**: [支付宝二维码](https://example.com/alipay)
- **微信支付**: [微信支付二维码](https://example.com/wechat)
- **PayPal**: [tongscriptx@example.com](mailto:tongscriptx@example.com)

## 🎁 赞助者福利

### 🏅 金牌赞助者 (≥ $50/月)
- 🌟 在 README 中特别鸣谢
- 🎮 优先体验新功能
- 📧 定期项目进展报告
- 🎯 影响项目发展方向
- 🏷️ 专属 Discord 身份组

### 🥈 银牌赞助者 (≥ $20/月)
- 🌟 在 README 中鸣谢
- 🎮 提前体验新功能
- 📧 月度进展报告
- 🏷️ Discord 身份组

### 🥉 铜牌赞助者 (≥ $5/月)
- 🌟 在赞助者列表中展示
- 📮 项目更新通知
- 🏷️ Discord 身份组

### 💝 支持者 (< $5/月)
- 📮 项目更新通知
- 🏷️ Discord 身份组

## 📊 资金用途

您的赞助将用于：

- 🛠️ **项目维护** - 修复 bug，优化性能
- 🚀 **新功能开发** - 添加更多游戏支持
- 📚 **文档完善** - 编写教程和指南
- 🌐 **服务器成本** - 维护在线服务
- 🎯 **社区建设** - 组织活动和比赛

## 🏆 当前赞助者

<!-- 这里会自动更新赞助者列表 -->

### 金牌赞助者
- 暂无

### 银牌赞助者  
- 暂无

### 铜牌赞助者
- 暂无

### 支持者
- 暂无

## 🙏 特别感谢

感谢所有为 Pluto 项目做出贡献的开发者和用户！

即使您无法提供资金赞助，以下方式同样宝贵：

- ⭐ 给项目点个 Star
- 🍴 Fork 项目并提交 PR
- 🐛 报告问题和建议
- 📝 完善文档和教程
- 💬 在社区中分享使用经验
- 📢 向朋友推荐项目

## 📞 联系我们

如有任何关于赞助的问题，欢迎联系：

- 📧 Email: [zhangfengqinzhangfengqin933@gmail.com](mailto:zhangfengqinzhangfengqin933@gmail.com)
- 💬 Discord: [加入我们的社区](https://discord.gg/)
- 🐛 GitHub: [提交 Issue](https://github.com/TongScriptX/Pluto/issues)

---

再次感谢您的支持！💖